apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy: {}
  template:
    metadata:
      labels:
          app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName}}
          image: {{ .Values.imageName }}
          ports:
            - containerPort: {{.Values.containerPort}}
          livenessProbe:
            httpGet:
              path: /v1/health
              port: {{.Values.containerPort}}
            periodSeconds: 60
          