apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{.Values.host }}
      http:
        paths:
          - path: /identity
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.serviceName }}
                port: 
                  number: {{ .Values.servicePort }}